### ISSUE TITLE
The name "SecureZip" is already in use.

### ISSUE THREAD

**Issue by madler** [kuviokelluja/DefuseZip#1]
"SecureZIP" is used by PKWare for their commercial product with strong encryption. (https://www.pkware.com/products/securezip) You should give this project a different name.

By the way, you can find modifications to Info-ZIP's unzip to detect zip bombs here: https://github.com/madler/unzip

**Comment by kuviokelluja** [comment]
Somehow this completely slipped my mind. I renamed the project to DefuseZip.
This project was mainly created to sate my curiosity, and I will study Info-ZIP to hopefully increase my knowledge.

Thank you.
